#!/usr/bin/env bash
# Daemora installer — one-shot setup for non-technical users.
#
# What this does, in order:
#   1. Detects Node.js; installs 22 LTS via the platform package manager
#      if missing or too old (Homebrew on macOS; apt/dnf/pacman on Linux).
#   2. Installs the `daemora` npm package globally so the `daemora` CLI
#      is on PATH.
#   3. Drops a small launcher script at ~/.daemora/bin/daemora-launcher
#      that starts the agent and waits for the HTTP port before opening
#      the browser.
#   4. Creates a desktop shortcut so the user can launch Daemora from
#      Applications / their app menu — `Daemora.app` on macOS,
#      `~/.local/share/applications/daemora.desktop` on Linux.
#   5. Runs the launcher so the dashboard opens immediately on first
#      install.
#
# First run: the launcher hits `daemora start`, which runs the existing
# setup wizard if config isn't done. Subsequent runs: the launcher just
# opens the browser (since the agent is already running) or restarts it
# if not.
#
# Usage:  curl -fsSL <url-to-this-script> | bash
# Env:    DAEMORA_PORT (default 8081)

set -euo pipefail

DAEMORA_PORT="${DAEMORA_PORT:-8081}"
LOG_PREFIX="[daemora-install]"

log()  { printf "%s %s\n" "$LOG_PREFIX" "$*"; }
err()  { printf "%s ERROR: %s\n" "$LOG_PREFIX" "$*" >&2; }
fail() { err "$*"; exit 1; }

OS="$(uname -s)"
case "$OS" in
  Darwin) PLATFORM=macos ;;
  Linux)  PLATFORM=linux ;;
  *)      fail "Unsupported OS: $OS. macOS and Linux are supported. Windows users: install.ps1." ;;
esac

# ── 1. Node.js ──────────────────────────────────────────────────────────
need_node() {
  if ! command -v node >/dev/null 2>&1; then return 0; fi
  local major
  major=$(node -p "process.versions.node.split('.')[0]" 2>/dev/null || echo 0)
  [ "$major" -lt 22 ]
}

install_node_macos() {
  if ! command -v brew >/dev/null 2>&1; then
    log "Homebrew not found — installing it (used to install Node.js)…"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  log "installing Node.js 22 via Homebrew…"
  brew install node@22 || brew install node
  brew link --overwrite --force node@22 2>/dev/null || true
}

install_node_linux() {
  log "installing Node.js 22 via your package manager…"
  if command -v apt-get >/dev/null 2>&1; then
    curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
    sudo apt-get install -y nodejs
  elif command -v dnf >/dev/null 2>&1; then
    curl -fsSL https://rpm.nodesource.com/setup_22.x | sudo -E bash -
    sudo dnf install -y nodejs
  elif command -v pacman >/dev/null 2>&1; then
    sudo pacman -Sy --noconfirm nodejs npm
  else
    fail "No supported package manager found (apt/dnf/pacman). Install Node.js 22+ from https://nodejs.org and rerun."
  fi
}

if need_node; then
  log "Node.js 22+ not found — installing…"
  if [ "$PLATFORM" = macos ]; then install_node_macos; else install_node_linux; fi
else
  log "Node.js $(node -v) detected — ok."
fi

# Some package-manager installs don't put npm on PATH for the current
# shell. Re-source common profile files so `npm` is available below.
hash -r 2>/dev/null || true

if ! command -v npm >/dev/null 2>&1; then
  fail "npm is not on PATH after installing Node. Open a new terminal and rerun the installer."
fi

# ── 2. daemora — global npm install ─────────────────────────────────────
log "installing Daemora (this may take a minute)…"
# Use sudo on Linux when npm's global prefix is a system path the user
# can't write to. macOS Homebrew prefixes are user-writable.
NPM_PREFIX="$(npm config get prefix 2>/dev/null || echo "")"
if [ "$PLATFORM" = linux ] && [ -n "$NPM_PREFIX" ] && [ ! -w "$NPM_PREFIX" ]; then
  sudo npm install -g daemora
else
  npm install -g daemora
fi

if ! command -v daemora >/dev/null 2>&1; then
  fail "Daemora installed but the \`daemora\` command isn't on PATH. Try opening a new terminal."
fi

# ── 3. Launcher ─────────────────────────────────────────────────────────
DAEMORA_HOME="$HOME/.daemora"
mkdir -p "$DAEMORA_HOME/logs" "$DAEMORA_HOME/bin"
LAUNCHER="$DAEMORA_HOME/bin/daemora-launcher"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Daemora launcher — starts the agent (if not already running) and opens
# the dashboard in the default browser. Generated by install.sh.
set -uo pipefail
LOG="\$HOME/.daemora/logs/daemora.log"
URL="http://localhost:${DAEMORA_PORT}"

open_url() {
  if [ "\$(uname -s)" = "Darwin" ]; then open "\$URL" 2>/dev/null
  else xdg-open "\$URL" 2>/dev/null || true
  fi
}

# If something is already serving on the port, just open the browser.
if curl -sf "\$URL" >/dev/null 2>&1; then
  open_url
  exit 0
fi

# Start daemora detached, log to ~/.daemora/logs/daemora.log.
mkdir -p "\$(dirname "\$LOG")"
( daemora start ) >> "\$LOG" 2>&1 &
PID=\$!

# Wait up to 30s for the HTTP port to come up.
for _ in \$(seq 1 30); do
  if curl -sf "\$URL" >/dev/null 2>&1; then break; fi
  sleep 1
done

open_url

# Keep the launcher attached so the .app process isn't orphaned —
# closing the launcher stops the agent.
wait \$PID
EOF
chmod +x "$LAUNCHER"

# ── 4. Desktop shortcut ─────────────────────────────────────────────────
if [ "$PLATFORM" = macos ]; then
  APP="/Applications/Daemora.app"
  log "creating $APP…"
  if [ ! -w /Applications ]; then SUDO=sudo; else SUDO=""; fi
  $SUDO mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
  $SUDO cp "$LAUNCHER" "$APP/Contents/MacOS/Daemora"
  $SUDO chmod +x "$APP/Contents/MacOS/Daemora"
  $SUDO tee "$APP/Contents/Info.plist" >/dev/null <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Daemora</string>
  <key>CFBundleDisplayName</key><string>Daemora</string>
  <key>CFBundleExecutable</key><string>Daemora</string>
  <key>CFBundleIdentifier</key><string>ai.daemora.app</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSUIElement</key><false/>
</dict>
</plist>
EOF
else
  DESKTOP="$HOME/.local/share/applications/daemora.desktop"
  mkdir -p "$(dirname "$DESKTOP")"
  log "creating $DESKTOP…"
  cat > "$DESKTOP" <<EOF
[Desktop Entry]
Name=Daemora
GenericName=AI Agent
Comment=Self-hosted AI agent — opens the dashboard in your browser.
Exec=$LAUNCHER
Type=Application
Categories=Utility;Development;
Terminal=false
StartupWMClass=Daemora
EOF
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
  fi
fi

# ── 5. Launch ───────────────────────────────────────────────────────────
log "all set. starting Daemora…"
nohup "$LAUNCHER" >/dev/null 2>&1 &
sleep 1
log ""
log "Daemora is running at http://localhost:${DAEMORA_PORT}"
log "Open it again any time from your apps menu (search \"Daemora\")."
